export const UPLOAD_USER_PROFILE = "profile/UPLOAD_USER_PROFILE";
export const UPDATE_USER_DISPLAYNAME = "profile/UPDATE_USER_DISPLAYNAME";
export const UPDATE_USER_UID = "profile/UPDATE_USER_UID";
export const UPDATE_USER_EMAIL = "profile/UPDATE_USER_EMAIL";
